### ISSUE TITLE
Type not parsed when array is explicit

### ISSUE THREAD

**Issue by woodp** [raml-org/raml-dotnet-parser-2#12]
RAML example:

```
  productPriceWithVariantsResponse:
    type: productPriceResponse
    properties:
      variantprices:
        type: array
        items: variantPrice
        required: false
```

Originally reported: https://github.com/mulesoft-labs/raml-dotnet-tools/issues/154
RAML Spec: https://github.com/mulesoft-labs/raml-dotnet-tools/files/1010839/api2.zip
